### ISSUE TITLE
Projects overview doesn't work on staging server

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#226]
Error while loading /en/projects

```
Internal Server Error: /en/projects/
Traceback (most recent call last):
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/response.py", line 80, in resolve_template
    return loader.get_template(template, using=self.using)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/template/loader_tags.py", line 174, in do_block
    raise TemplateSyntaxError("'%s' tag takes only one argument" % bits[0])
django.template.base.TemplateSyntaxError: 'block' tag takes only one argument
```

**Comment by slomo** [comment]
fixed, propably some merge artifacts

**Comment by slomo** [comment]
PR wasn't merged yet
