### ISSUE TITLE
Image upload doesn't accept images with umlauts

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#227]
Stacktrace from stage server

```
Internal Server Error: /de/ideas/create/module/water_saving_in_Slovenia/
Traceback (most recent call last):
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/braces/views/_access.py", line 102, in dispatch
    request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/home/wagtail/wagtail/euth/ideas/views.py", line 62, in form_valid
    return super().form_valid(form)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/edit.py", line 193, in form_valid
    self.object = form.save()
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/forms/models.py", line 459, in save
    construct=False)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/forms/models.py", line 105, in save_instance
    instance.save()
  File "/home/wagtail/wagtail/euth/ideas/models.py", line 27, in save
    super(Idea, self).save(*args, **kwargs)
  File "/home/wagtail/wagtail/euth/contrib/base_models.py", line 16, in save
    super(TimeStampedModel, self).save(*args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/db/models/base.py", line 824, in _save_table
    for f in non_pks]
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/db/models/base.py", line 824, in <listcomp>
    for f in non_pks]
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/db/models/fields/files.py", line 314, in pre_save
    file.save(file.name, file, save=False)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/core/files/storage.py", line 53, in save
    name = self.get_available_name(name, max_length=max_length)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/core/files/storage.py", line 89, in get_available_name
    while self.exists(name) or (max_length and len(name) > max_length):
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/core/files/storage.py", line 294, in exists
    return os.path.exists(self.path(name))
  File "/home/wagtail/wagtail/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 43: ordinal not in range(128)
```

**Comment by slomo** [comment]
Fixed by adding `en_US.UTF-8`, `LC_ALL=en_US.UTF-8` and `LC_LANG=en_US.UTF-8` as env vars
